---
site_name: "Understanding OT networks & unfold the OT network jungle"
site_description: Understanding OT networks & unfold the OT network jungle
strict: true
nav:
  - Overview: "index.md"
  - Agenda: "agenda.md"
  - Slides: "slides.md"
  - Lab: "lab.md"
  - Cheatsheet: "cheatsheet.md"
  - Container101: "Container101.md"
  - Automation: "automation.md"
  - Feedback: "feedback.md"



repo_url: https://github.com/narrowin/ot-labs-isc-cph-2025
repo_name: OT-LABS


theme:
  name: material
  logo: img/narrowin.svg
  favicon: img/favicon.ico
  palette:
    # - scheme: slate
    #   primary: custom
    #   accent: custom

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tracking

extra:
  homepage: https://narrowin.ch/explorer

extra_css:
  - stylesheets/extra.css

plugins:
  - offline:
      enabled: true

#plugins:
    # - with-pdf:
    #     author: Martin Scheu, Mischa Diehm, Christopher Scherb
    #     copyright: ""
    #     cover_subtitle: OT Attack Mapping & Risk-Based Defense

    #     output_path: ot-sec-workshop.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        # debug_html: true
        #show_anchors: true
        # verbose: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
